// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  home: {
    'GitHub Actions': [
      'about',
      'resources',
    ]
  },
  
  tutorials: [
    {
      type: 'category',
      label: 'Today I Learned',
      items: [{
          type: 'autogenerated',
          dirName: 'tutorials',
      }],
    }
  ],
  
  misc:{
    'Misc': [
        {
          type: 'category',
          label: 'Random Stuff',
          items: [{
              type: 'autogenerated',
              dirName: 'misc',
          }],
        },
      ]
  }
};

module.exports = sidebars;