// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  
  concepts: [
    {
      type: 'category',
      label: 'What Is',
      items: [{
          type: 'autogenerated',
          dirName: 'concepts',
      }],
    },
  ],

  tutorials: [
    {
      type: 'category',
      label: 'How To ::',
      items: [{
          type: 'autogenerated',
          dirName: 'tutorials',
      }],
    },
  ],
  
  /*
  misc:{
    'Misc': [
        {
          type: 'category',
          label: 'Random Stuff',
          items: [{
              type: 'autogenerated',
              dirName: 'misc',
          }],
        },
      ]
  }
  */
};

module.exports = sidebars;