// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  home: {
    'Roadmap': [
      'about',
      'resources',
    ]
  },

  sidebar1: {
    'Concepts': [
        {
          type: 'autogenerated',
          dirName: 'concepts',
        },
      ],
  },
  
  sidebar2:{
    'Tutorials': [
      'tutorials/toc',
      {
        type: 'category',
        label: 'Beginner',
        items: [{
            type: 'autogenerated',
            dirName: 'tutorials/beginner',
        }],
      },
      {
        type: 'category',
        label: 'Advanced',
        items: [{
            type: 'autogenerated',
            dirName: 'tutorials/advanced',
        }],
      },
    ],
  },
  
  sidebar3:{
    'Solutions': [
      {
        type: 'autogenerated',
        dirName: 'solutions',
      },
    ],
  },

  /*
  sidebar4:{
    'Misc': [
        {
          type: 'category',
          label: 'Random Stuff',
          items: [{
              type: 'autogenerated',
              dirName: 'misc',
          }],
        },
      ]
  }
  */
  
};

module.exports = sidebars;